name: pcbuilder
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  share_plus: ^10.1.4
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.0.11
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_image.png"  # Path to your icon
  adaptive_icon_background: "#ffffff"     # (Optional) Adaptive icon background

flutter:
  uses-material-design: true
